# Nome do workflow, aparece na 'Actions'
name: pipeline CI/CD
# Definir quando o pipeline sera disparado
on: 
  push:
    branches:
      - main
    paths: #so dispara se arquicos nessas pastas mudarem
      -'src/**' #so mudanças no codigo fontes
      -'.github/workflows/**' #mudnças nos proprios pipelines
  workflow_dispatch: #habilitar o botão 'run workflow' no github actiond
  
jobs:
  #Primeiro job: build
  build:
    runs-on: ubuntu-latest #imagem da maquina usada no CI
    
    steps:
      - name: checkout do codigo
        uses: actions/checkout@v6

      - name: Istalação do node 
        uses: actions/setup-node@v4
        
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Istalação das depêndencias
        run: npm install
        
      - name: Rodar o build
        run: npm run build 

    teste:
      runs-on: ubuntu-latest #imagem da maquina usada no CI
      needs: build

    steps:
      - name: checkout do codigo
        uses: actions/checkout@v6

      - name: Istalação do node 
        uses: actions/setup-node@v4
        
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          
      - name: Istalação das depêndencias
        run: npm install

      - name: Rodar lint
        run: npm run lint

      - name: Verificar formatação
        run: npm run format -- -- check

      - name: Rodar Teste
        run: npm run test

        
        
