name: pipeline CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Rodar lint
        run: npm run lint

      - name: Rodar testes
        run: npm run test

      - name: Rodar build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Deploy na Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
